".\tools\lc\recomp.exe" "./gfx/en/lz_title_gfx.bin" "./gfx/en/lz/lz_title_gfx.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_title_map.bin" "./gfx/en/lz/lz_title_map.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_subtitle_gfx.bin" "./gfx/en/lz/lz_subtitle_gfx.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_intro_gfx1.bin" "./gfx/en/lz/lz_intro_gfx1.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_intro_gfx2.bin" "./gfx/en/lz/lz_intro_gfx2.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_intro_map.bin" "./gfx/en/lz/lz_intro_map.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_teamname_map.bin" "./gfx/en/lz/lz_teamname_map.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_credits_gfx.bin" "./gfx/en/lz/lz_credits_gfx.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_credits_map.bin" "./gfx/en/lz/lz_credits_map.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_colonel_note_gfx1.bin" "./gfx/en/lz/lz_colonel_note_gfx1.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_colonel_note_gfx2.bin" "./gfx/en/lz/lz_colonel_note_gfx2.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_gina_ransom_gfx.bin" "./gfx/en/lz/lz_gina_ransom_gfx.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_patchy_note_gfx.bin" "./gfx/en/lz/lz_patchy_note_gfx.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_camp_tips_gfx.bin" "./gfx/en/lz/lz_camp_tips_gfx.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_controls_gfx.bin" "./gfx/en/lz/lz_controls_gfx.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_ship_notes_gfx.bin" "./gfx/en/lz/lz_ship_notes_gfx.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_chorelistmisc_map.bin" "./gfx/en/lz/lz_chorelistmisc_map.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_bensongrave_gfx.bin" "./gfx/en/lz/lz_bensongrave_gfx.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_monsterposter_gfx.bin" "./gfx/en/lz/lz_monsterposter_gfx.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_chorelist_gfx.bin" "./gfx/en/lz/lz_chorelist_gfx.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_officesign_map.bin" "./gfx/en/lz/lz_officesign_map.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_officesign_gfx.bin" "./gfx/en/lz/lz_officesign_gfx.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en/lz_nintendo_gfx.bin" "./gfx/en/lz/lz_nintendo_gfx.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en_new/lz_teamname_map.bin" "./gfx/en_new/lz/lz_teamname_map.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en_new/lz_subtitle_gfx.bin" "./gfx/en_new/lz/lz_subtitle_gfx.bin.lz" 0 1 0
".\tools\lc\recomp.exe" "./gfx/en_new/lz_nintendo_gfx.bin" "./gfx/en_new/lz/lz_nintendo_gfx.bin.lz" 0 1 0